[workspace]

members = [
    "clearing_connection",
    "clearing_engine",
    "client",
    "dbhook",
    "disseminator",
    "gateway",
    "instruments",
    "matching_engine",
    "market",
    "order",
    "oep",
    "utils",
]
resolver = "2"
